### ISSUE TITLE
Poolstats table - no hashrates and miners recorded

### ISSUE THREAD

**Issue by Hoellschrei** [DirtyHarryDev/miningcore#2]
The pool seems to run fine and my miner submits shares, but the minerstats and poolstats table look a bit strange. Minerstats is empty and poolstats looks like this:

id |	poolid |	connectedminers |	poolhashrate |	sharespersecond |	networkhashrate |	networkdifficulty |	lastnetworkblocktime |	blockheight |	connectedpeers |	created
7878 |	test | 0 | 0 | 0 |940295661.3053098 | 497.404607311215 | 2021-01-24 20:39:49.063344	|1519991 | 8 |2021-01-24 20:39:49.394512

connectedminers, poolhashrate and sharespersecond are empty.

Any idea what's going on? Shares table is filled with data.

**Comment by Hoellschrei** [comment]
uuh...I compiled the following sources (as written in the HowTo):
git clone https://github.com/DirtyHarryDev/miningcore-new miningcore

but...miningcore-new is now marked with a "not-working"

I'll rebuild it from https://github.com/DirtyHarryDev/miningcore

**Comment by Hoellschrei** [comment]
With this (https://github.com/DirtyHarryDev/miningcore) version compiled, I have exeptions in the logfile:

[2021-01-24 21:38:38.4763] [E] [StatsRecorder] Npgsql.PostgresException (0x80004005): 42703: column "connectedworkers" of relation "poolstats" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 687

I'll try adding the missing column

**Comment by Hoellschrei** [comment]
ok, now it's working fine. Tables are filled.
